### ISSUE TITLE
Citation feature for population models

### ISSUE THREAD

**Issue by scottperkins** [LLNL/popclass#46]
We could include a metadata tag in the population files to include a DOI entry, with an added citation() method in population model that prints the DOI for citing specific models.

**Comment by astrophpeter** [comment]
Tasks that need to be completed for this:

1. update asdf model files in /data/ to include a citation field that is a list of strings.
2. Add relevant citations DOIs, for all three current models are ["10.3847/1538-4357/ab5fd3", "10.3847/1538-4357/aca09d"], to the current asdf files. Probably should read them in add the field and save them, then commit the new model files
3. update validate_asdf_population_model to include a checks for this field
4. update all docs and mention this field
5. add citation (property) method to PopulationModel which returns this list of DOIs for a given model. Add tests to test this functionality. You will also need to modify PopulationModel __init__ and from_asdf and to_asdf to include citations parameters and save/write them. Update tests accordingly.

**Comment by astrophpeter** [comment]
Larger one this time @caitlinbegbie  :)
